<h1>Laboratory work 2 </h1>
<h2>Satanova Munira AIN-2-21</h2>
<h3> Using NumPy library commands </h3>

In [6]:
import numpy as np

 1. Create a one-dimensional array my_array that contains, in order, all numbers up to 100 that are divisible by 5

In [37]:
my_array = np.arange(5, 101, 5)
print("1. my_array:", my_array)

1. my_array: [  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


2. From the resulting array get an array with multiples of 10 numbers

In [38]:
my_array_10 = my_array[my_array % 10 == 0]
print("2. my_array_10:", my_array_10)

2. my_array_10: [ 10  20  30  40  50  60  70  80  90 100]


3. Get a two-dimensional array with two columns

In [39]:
my_2d_array = my_array.reshape(-1, 2)
print("3. my_2d_array:\n", my_2d_array)

3. my_2d_array:
 [[  5  10]
 [ 15  20]
 [ 25  30]
 [ 35  40]
 [ 45  50]
 [ 55  60]
 [ 65  70]
 [ 75  80]
 [ 85  90]
 [ 95 100]]


4. Get a set my_second_array in which all elements are smaller than the previous initial set by 5

In [40]:
my_second_array = my_array - 5
print("4. my_second_array:", my_second_array)

4. my_second_array: [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


    5. Connect the arrays obtained in steps 3 and 4 horizontally. Use .T to transpose the matrix.

In [51]:
# Combine the arrays horizontally
combined_array = np.hstack((my_2d_array, my_second_array.reshape(-1, 2)))

# Transpose the matrix
combined_array = combined_array.T

print("5. combined_array:\n", combined_array)

5. combined_array:
 [[ 10   0  25  35  45  55  65  75  85  95]
 [ 20  10  30  40  50  60  70  80  90 100]
 [  0  10  20  30  40  50  60  70  80  90]
 [  5  15  25  35  45  55  65  75  85  95]]


6. Split row 2 and row 3 into the top 4 rows of my_array. Use .T to transpose the matrix

In [46]:
# Split row 2 and row 3 into the top 4 elements of my_array
my_array[0:2] = combined_array[1, :2]  # Split row 2
my_array[2:4] = combined_array[2, :2]  # Split row 3

print(my_array)

[ 10  20   0  10  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


    7. Leave only those values that have not changed after division

In [60]:
unchanged_values = combined_array[:, 0] == combined_array[:, 1]
filtered_array = combined_array[unchanged_values]
print("7. filtered_array:\n", filtered_array)

7. filtered_array:
 []


8. Get a three-line two-dimensional array again and swap the first and third lines

In [62]:
final_array = filtered_array.reshape(3, -1)
final_array[[0, 2]] = final_array[[2, 0]]
print("8. final_array:\n", final_array)

8. final_array:
 []


9. Obtain the mean, median and standard deviation for each row

In [63]:
mean_values = np.mean(final_array, axis=1)
median_values = np.median(final_array, axis=1)
std_deviation_values = np.std(final_array, axis=1)


C:\Users\Asus\PycharmProjects\bigDataLabs\venv\Lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\Asus\PycharmProjects\bigDataLabs\venv\Lib\site-packages\numpy\core\_methods.py:121: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
C:\Users\Asus\PycharmProjects\bigDataLabs\venv\Lib\site-packages\numpy\core\_methods.py:206: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
C:\Users\Asus\PycharmProjects\bigDataLabs\venv\Lib\site-packages\numpy\core\_methods.py:163: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean,
C:\Users\Asus\PycharmProjects\bigDataLabs\venv\Lib\site-packages\numpy\core\_methods.py:195: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(


10. Normalize to the maximum value along the rows

In [27]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Нормализация на максимальное значение вдоль строк
normalized_array = array / array.max(axis=1, keepdims=True)

print(normalized_array)


[[0.33333333 0.66666667 1.        ]
 [0.66666667 0.83333333 1.        ]
 [0.77777778 0.88888889 1.        ]]


Results output

<h3>Using pandas library commands</h3>

In [2]:
import pandas as pd

Import the data from the file "Global Population Trends(2016-2022).csv":

In [3]:
# Replace 'path_to_file' with the actual path to the CSV file
df = pd.read_csv('Global Population Trends(2016-2022).csv')

Read the first few entries of the table:

In [4]:
print(df.head())

       Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55            63.0      37.342       7.027          5.129   
1                 56            63.0      36.927       6.981          5.002   
2                 58            64.0      36.466       6.791           4.87   
3                 60            63.0      36.051       7.113           4.75   
4                  -            62.0      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0                  49.4           - 

Determine the dimensionality of this frame:

In [5]:
print(df.shape)

(1073, 12)


Print the names of the frame's column headers:

In [64]:
print(df.columns)

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')


Get a description of all variables (fields):

In [65]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1073 entries, 0 to 1072
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Country                1073 non-null   object 
 1   Year                   1073 non-null   int64  
 2   Total Population       1073 non-null   object 
 3   Urban Population       1073 non-null   object 
 4   Rural Population       1073 non-null   object 
 5   Population Density     1073 non-null   object 
 6   Life Expectancy        1073 non-null   object 
 7   Birth Rate             1073 non-null   float64
 8   Death Rate             1073 non-null   float64
 9   Fertility Rate         1073 non-null   object 
 10  Infant Mortality Rate  1073 non-null   object 
 11  Growth Rate            1073 non-null   object 
dtypes: float64(2), int64(1), object(9)
memory usage: 100.7+ KB
None


Delete rows that do not contain a value in the Total Population column:

In [66]:
df = df[df['Total Population'] != '-']

Obtain descriptive statistics on the variables:

In [67]:
print(df.describe())

              Year  Birth Rate  Death Rate
count   864.000000  864.000000  864.000000
mean   2019.500000   18.548384    7.889123
std       1.118682    9.887518    3.041385
min    2018.000000    0.000000    0.000000
25%    2018.750000   10.500000    6.116500
50%    2019.500000   15.628500    7.453500
75%    2020.250000   25.565000    9.385000
max    2021.000000   46.127000   21.700000


Sort the data by several criteria. For example, you can sort the data by the column "Total Population" in descending order:

In [68]:
df = df.sort_values(by='Total Population', ascending=False)

Output the name of the country that has the maximum population:

In [70]:
max_population_country = df.loc[df['Total Population'].idxmax()]['Country']
print("Country with maximum population:", max_population_country)

Country with maximum population: Seychelles


Output the name of the country that has the minimum population:

In [72]:
min_population_country = df.loc[df['Total Population'].idxmin()]['Country']
print("Country with minimum population:", min_population_country)

Country with minimum population: Djibouti


Export the frame to MS Excel. For example, you can save the frame to the file "population_data.xlsx":

In [76]:
df.to_excel('Global Population Trends(2016-2022).xlsx', index=False)